// Yume Forge — drawn crystal generator.
//
//   node tools/crystal.mjs
//
// Writes sprites/crystal.css. This is the fallback/original-art crystal;
// `python3 tools/rip-assets.py` writes the same file from crystal.png.
//
// It lives apart from tools/ambience.mjs on purpose: ambience needs to be
// re-runnable whenever the starfield or moon changes, and it used to take the
// crystal with it — silently reverting a ripped crystal back to this one.

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const W = 24;
const H = 32;

/** Faceted crystal, built to be tinted by drop-shadow rather than recoloured. */
const svg =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}">` +
  `<path fill="#1f9fd0" d="M12 0 24 13 12 32 0 13Z"/>` +
  `<path fill="#8beaff" d="M12 0 12 32 0 13Z"/>` +
  `<path fill="#59d8f7" d="M12 0 24 13 12 32Z" opacity=".55"/>` +
  `<path fill="#eafcff" d="M12 2 17 13 12 21 7 13Z" opacity=".92"/>` +
  `<path fill="#ffffff" d="M12 2 14 12 12 16 10 12Z"/>` +
  `</svg>`;

const toDataUri = (s) =>
  "data:image/svg+xml," +
  encodeURIComponent(s)
    .replace(/'/g, "%27").replace(/%20/g, " ").replace(/%3D/g, "=")
    .replace(/%3A/g, ":").replace(/%2F/g, "/");

const css = `/* GENERATED by tools/crystal.mjs — do not edit by hand.
   Hand-drawn faceted crystal, ${W}x${H}.

   Re-run \`python3 tools/rip-assets.py\` to use crystal.png instead. */

:root {
  --yume-ff-crystal: url("${toDataUri(svg)}");
  --yume-ff-crystal-w: ${W};
  --yume-ff-crystal-h: ${H};
}
`;

await mkdir(resolve(ROOT, "sprites"), { recursive: true });
await writeFile(resolve(ROOT, "sprites/crystal.css"), css, "utf8");

console.log(`crystal ${W}x${H} — ${svg.length}b svg -> sprites/crystal.css`);
