// Yume Forge — menu cursor generator.
//
//   node tools/cursor.mjs
//
// Draws the pointing-hand select cursor and writes it to sprites/cursor.css.
//
// Unlike tools/sprites.mjs this does NOT auto-outline: the hand carries its own
// black keyline as part of the art, and running the silhouette pass over it
// would wrap a second ring around the outside.
//
// The hand points RIGHT here. Consumers mirror it with scaleX(-1) where a
// left-pointing cursor reads better.
//
// tools/rip-assets.py will override this file if a hand/cursor PNG is dropped
// in the repo root — same last-one-wins arrangement as the party sheet.

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const PALETTE = {
  ".": null,
  K: "#000000", // keyline
  W: "#ffffff", // highlight
  G: "#a6a6ae", // shading
};

const WIDTH = 16;

// Classic select hand: rounded knuckle on top, one thick pointing finger, fist
// bulging down-left with shading along the underside.
//
// The finger needs a clear notch where it meets the fist (rows 3 and 6) —
// without it the whole shape reads as an undifferentiated blob at icon sizes,
// which is exactly how the first pass looked.
const HAND = [
  "......KKK.......",
  ".....KWWWK......",
  "....KWWWWWK.....",
  "....KWWWWWKKKKK.",
  "...KWWWWWWWWWWWK",
  "...KWWWWWWWWWWWK",
  "...KWWWWWWWKKKKK",
  "..KGWWWWWWWK....",
  "..KGGWWWWWWK....",
  ".KGGGWWWWWWK....",
  ".KGGGGGWWWWK....",
  ".KGGGGGGGGGK....",
  "..KGGGGGGGK.....",
  "...KKKKKKK......",
];

function validate(rows) {
  rows.forEach((row, i) => {
    if (row.length !== WIDTH) throw new Error(`row ${i} is ${row.length} wide, expected ${WIDTH}`);
    for (const c of row) if (!(c in PALETTE)) throw new Error(`row ${i}: unknown key "${c}"`);
  });
}

/** Run-length merge each row, bucketed by colour, one <path> per colour. */
function build(rows) {
  const buckets = {};
  rows.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const key = row[x];
      if (!PALETTE[key]) { x++; continue; }
      let run = 1;
      while (x + run < row.length && row[x + run] === key) run++;
      (buckets[key] ||= []).push(`M${x} ${y}h${run}v1h-${run}z`);
      x += run;
    }
  });
  const paths = Object.entries(buckets)
    .map(([k, d]) => `<path fill="${PALETTE[k]}" d="${d.join("")}"/>`)
    .join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${WIDTH}" height="${rows.length}" ` +
         `viewBox="0 0 ${WIDTH} ${rows.length}" shape-rendering="crispEdges">${paths}</svg>`;
}

const toDataUri = (svg) =>
  "data:image/svg+xml," +
  encodeURIComponent(svg)
    .replace(/'/g, "%27").replace(/%20/g, " ").replace(/%3D/g, "=")
    .replace(/%3A/g, ":").replace(/%2F/g, "/");

validate(HAND);
const svg = build(HAND);

const css = `/* GENERATED by tools/cursor.mjs — do not edit by hand.
   Pointing-hand select cursor, ${WIDTH}x${HAND.length}, pointing RIGHT.
   Mirror with transform: scaleX(-1) where a left-pointing hand reads better.

   Re-run \`python3 tools/rip-assets.py\` to use a hand PNG from the repo root. */

:root {
  --yume-ff-cursor: url("${toDataUri(svg)}");
  --yume-ff-cursor-w: ${WIDTH};
  --yume-ff-cursor-h: ${HAND.length};
}
`;

await mkdir(resolve(ROOT, "sprites"), { recursive: true });
await writeFile(resolve(ROOT, "sprites/cursor.css"), css, "utf8");

console.log(`cursor ${WIDTH}x${HAND.length} — ${svg.length}b svg -> sprites/cursor.css`);
