#!/usr/bin/env python3
"""Yume Forge — extract the big menu crystal from menu-crystal.png.

    python3 tools/rip-menu-crystal.py

Input: sources/sprites/menu-crystal.png — a 256x256 pixel-art crystal on flat
black. The black is keyed out (the art itself uses pure black only as its
outline INSIDE the silhouette, so keying is flood-based from the borders, not
colour-based — a colour key would hollow out the linework).

The art is an upscale of a small native grid; modal run-length recovers the
cell size and a majority vote downsamples, exactly like the other rippers.

Output: sprites/menu-crystal.css with --yume-ff-menu-crystal (+ -w/-h).
Used for the sidebar's feedback button, where the pointing hand used to be.
"""

import base64
import io
from collections import Counter
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "sources/sprites/menu-crystal.png"
OUT = ROOT / "sprites/menu-crystal.css"

img = Image.open(SRC).convert("RGBA")
w, h = img.size
px = img.load()

# Flood the background black in from the borders; interior black linework is
# enclosed by the crystal body and never reached.
BLACK = (0, 0, 0, 255)
stack = [(x, y) for x in range(w) for y in (0, h - 1)] + \
        [(x, y) for y in range(h) for x in (0, w - 1)]
seen = [[False] * w for _ in range(h)]
while stack:
    x, y = stack.pop()
    if not (0 <= x < w and 0 <= y < h) or seen[y][x] or px[x, y] != BLACK:
        continue
    seen[y][x] = True
    px[x, y] = (0, 0, 0, 0)
    stack += [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]

# Native grid recovery: modal run length across rows.
runs = Counter()
for y in range(h):
    x = 0
    while x < w:
        r = 1
        while x + r < w and px[x + r, y] == px[x, y]:
            r += 1
        if r >= 4:
            runs[r] += 1
        x += r
freq = [r for r, c in runs.items() if c >= 3]
cell = min(freq) if freq else 8

bbox = img.getbbox()
img = img.crop(bbox)
nw, nh = max(1, round(img.width / cell)), max(1, round(img.height / cell))
src_px = img.load()
out = Image.new("RGBA", (nw, nh), (0, 0, 0, 0))
dst = out.load()
for y in range(nh):
    y0, y1 = int(y * img.height / nh), max(int(y * img.height / nh) + 1, int((y + 1) * img.height / nh))
    for x in range(nw):
        x0, x1 = int(x * img.width / nw), max(int(x * img.width / nw) + 1, int((x + 1) * img.width / nw))
        votes = Counter(src_px[sx, sy] for sy in range(y0, y1) for sx in range(x0, x1))
        dst[x, y] = votes.most_common(1)[0][0]

buf = io.BytesIO()
out.save(buf, format="PNG", optimize=True)
raw = buf.getvalue()
out.save(ROOT / "sprites/menu-crystal.png")
uri = "data:image/png;base64," + base64.b64encode(raw).decode("ascii")

OUT.write_text(
    "/* GENERATED by tools/rip-menu-crystal.py — do not edit by hand.\n"
    f"   Source: menu-crystal.png ({cell}x upscale, resampled to "
    f"{out.width}x{out.height} native). */\n\n"
    ":root {\n"
    f'  --yume-ff-menu-crystal: url("{uri}");\n'
    f"  --yume-ff-menu-crystal-w: {out.width};\n"
    f"  --yume-ff-menu-crystal-h: {out.height};\n"
    "}\n",
    encoding="utf8",
)
print(f"menu crystal {out.width}x{out.height} native (cell {cell}px, {len(raw)}b png)")
