#!/usr/bin/env python3
"""Yume Forge — extract the chocobo run cycle from choco.png.

    python3 tools/rip-choco.py

Input: sources/sprites/choco.png — a 19-frame chocobo sheet on flat magenta
(255,0,255 — note: NOT the battle sheet's 255,5,238). Components are detected
and ordered exactly like the other rippers.

The run pair, picked from an 8x render of every side-facing frame: frame 8
(full stride — legs split, body leaning into the run) and frame 5 (legs
gathered, wing flared mid-flap). The first eyeballed pick, 1+15, turned out to
be two near-identical standing frames that animated as a nervous shuffle.
Both face LEFT natively; the theme mirrors with scaleX(-1) for left-to-right
runs. Frames share one union crop box, bottom-aligned, so the gait doesn't
jitter vertically.

Output: sprites/chocobo.css with --yume-ff-choco (2-frame strip) and
-w/-h cell dims as plain numbers (calc(var(..) * 1px) at the use site).
"""

import base64
import io
import json
from collections import deque
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "sources/sprites/choco.png"
OUT = ROOT / "sprites/chocobo.css"

EXPECT_FRAMES = 19
RUN_FRAMES = (8, 5)    # stride, gathered+flap — reading-order component indices

KEY = (255, 0, 255)
KEY_TOL = 12
MIN_PX = 30


def main():
    img = Image.open(SRC).convert("RGBA")
    px = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if abs(r - KEY[0]) <= KEY_TOL and abs(g - KEY[1]) <= KEY_TOL and abs(b - KEY[2]) <= KEY_TOL:
                px[x, y] = (0, 0, 0, 0)

    seen = [[False] * w for _ in range(h)]
    boxes = []
    for y0 in range(h):
        for x0 in range(w):
            if seen[y0][x0] or px[x0, y0][3] == 0:
                continue
            q = deque([(x0, y0)])
            seen[y0][x0] = True
            mnx = mxx = x0
            mny = mxy = y0
            n = 0
            while q:
                cx, cy = q.popleft()
                n += 1
                mnx, mxx = min(mnx, cx), max(mxx, cx)
                mny, mxy = min(mny, cy), max(mxy, cy)
                for dx in (-2, -1, 0, 1, 2):
                    for dy in (-2, -1, 0, 1, 2):
                        nx, ny = cx + dx, cy + dy
                        if 0 <= nx < w and 0 <= ny < h and not seen[ny][nx] and px[nx, ny][3] != 0:
                            seen[ny][nx] = True
                            q.append((nx, ny))
            if n >= MIN_PX:
                boxes.append((mnx, mny, mxx + 1, mxy + 1))

    boxes.sort(key=lambda b: (b[1] + b[3]) / 2)
    rows, cur = [], [boxes[0]]
    for b in boxes[1:]:
        if abs((b[1] + b[3]) / 2 - (cur[-1][1] + cur[-1][3]) / 2) <= 12:
            cur.append(b)
        else:
            rows.append(cur)
            cur = [b]
    rows.append(cur)
    ordered = []
    for r in rows:
        ordered.extend(sorted(r, key=lambda b: b[0]))

    if len(ordered) != EXPECT_FRAMES:
        raise SystemExit(
            f"expected {EXPECT_FRAMES} frames in {SRC.name}, found {len(ordered)} — "
            "the sheet changed; re-derive RUN_FRAMES before regenerating."
        )

    frames = [img.crop(ordered[i]) for i in RUN_FRAMES]
    cw = max(f.width for f in frames)
    ch = max(f.height for f in frames)
    strip = Image.new("RGBA", (cw * len(frames), ch), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        # Bottom-aligned, centred: the feet stay on one baseline between
        # frames, which is what makes the gait read as running rather than
        # bouncing.
        strip.paste(f, (i * cw + (cw - f.width) // 2, ch - f.height), f)

    buf = io.BytesIO()
    strip.save(buf, format="PNG", optimize=True)
    raw = buf.getvalue()
    uri = "data:image/png;base64," + base64.b64encode(raw).decode("ascii")
    strip.save(ROOT / "sprites/chocobo.png")

    OUT.write_text(
        "/* GENERATED by tools/rip-choco.py — do not edit by hand.\n"
        f"   2-frame run cycle (sheet frames {RUN_FRAMES[0]} and {RUN_FRAMES[1]} of\n"
        f"   {EXPECT_FRAMES}), cell {cw}x{ch}, bottom-aligned. Faces LEFT natively;\n"
        "   mirror with scaleX(-1) to run rightward. */\n\n"
        ":root {\n"
        f'  --yume-ff-choco: url("{uri}");\n'
        f"  --yume-ff-choco-w: {cw};\n"
        f"  --yume-ff-choco-h: {ch};\n"
        "}\n",
        encoding="utf8",
    )
    print(f"choco strip {cw}x{ch} x{len(frames)} frames ({len(raw)}b png)")


if __name__ == "__main__":
    main()
