// Yume Forge — package the bottom horizon silhouette.
//
//   node tools/silhouette.mjs
//
// Input: sources/sprites/bottom_silhouette_vector.svg — a single-path,
// pixel-edged scene (the party on a cliff at the right, a town skyline off to
// the left). Provided art, not generated; this script only recolors, minifies
// and inlines it.
//
// Output: sprites/silhouette.css with --yume-ff-silhouette (+ -w/-h as plain
// numbers, matching the other sprite sheets' convention of calc(var(..) * 1px)
// at the use site).
//
// The fill is swapped from #000000 to a deep navy: pure black against the
// theme's night sky reads as a hole in the page, the navy reads as land at
// night. The right edge of the ART is what anchors to the viewport's right,
// so the figures stay on screen at any width and widening reveals the town.

import { readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "sources/sprites/bottom_silhouette_vector.svg");
const OUT = resolve(ROOT, "sprites/silhouette.css");

const FILL = "#04071c";

let svg = await readFile(SRC, "utf8");

const vb = /viewBox="0 0 (\d+) (\d+)"/.exec(svg);
if (!vb) throw new Error("no viewBox in the source svg");
const [w, h] = [vb[1], vb[2]];

svg = svg
  .replace(/<\?xml[^?]*\?>\s*/, "")
  .replace(/fill="#000000"/g, `fill="${FILL}"`)
  // The path data is written as "M 1566 123 L 1566 128" — the spaces around
  // command letters are optional, and dropping them takes a third off the
  // file before encoding.
  .replace(/\s*([MLZz])\s*/g, "$1")
  .replace(/\s+/g, " ")
  .replace(/> </g, "><")
  .trim();

const uri = "data:image/svg+xml;base64," + Buffer.from(svg).toString("base64");

await writeFile(OUT,
  `/* GENERATED by tools/silhouette.mjs — do not edit by hand.
   Source: bottom_silhouette_vector.svg (${w}x${h}), fill recolored to ${FILL}.
   Anchored right-bottom by the theme so the right of the scene never leaves
   the screen; widening the window reveals more of the left. */

:root {
  --yume-ff-silhouette: url("${uri}");
  --yume-ff-silhouette-w: ${w};
  --yume-ff-silhouette-h: ${h};
}
`, "utf8");

console.log(`wrote sprites/silhouette.css (${w}x${h}, ${(uri.length / 1024).toFixed(1)}KB data URI)`);
